---
# build-servers.yml
- hosts: devbox
  #Define user and password variables
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("guest123", "guest")'
    password : deZglJ0UD./IQ
    user : devbox
  roles:
    - users
    - common
    - docker
    - node
    - python
    - drone-cli
#  environment:
#    http_proxy: http://proxy-rtp-1.cisco.com:8080
#    https_proxy: http://proxy-rtp-1.cisco.com:8080
