# common.yml
---

- name: Install dependencies
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - git
    - curl
    - openssl-devel

- name: install the 'Gnome desktop' environment group
  yum:
    name: "@^gnome-desktop-environment"
    state: present
  become: yes

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present
  become: yes
