# common.yml
---

- name: Install dependencies
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - git
    - curl
    - openssl-devel

- name: install the 'Gnome desktop' environment group
  yum:
    name: "@^gnome-desktop-environment"
    state: present
  become: yes

- name: set GUI to launch on startup
  become: yes
  command: "systemctl set-default graphical.target"

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present
  become: yes

- name: create (shortcut) directory
  become: yes
  become_user: "{{ general.user }}"
  file:
    path: "/home/{{ general.user }}/Desktop"
    state: directory
  tags:
    - configuration

- name: install firfox shortcuts
  become: yes
  become_user: "{{ general.user }}"
  template:
    src: "roles/common/templates/firefox.desktop.j2"
    dest: /home/{{ general.user }}/Desktop/firefox.desktop
    owner: "{{ general.user }}"
    mode: 0755
  tags:
    - configuration

- name: install terminal shortcuts
  become: yes
  become_user: "{{ general.user }}"
  template:
    src: "roles/common/templates/gnome-terminal.desktop.j2"
    dest: /home/{{ general.user }}/Desktop/gnome-terminal.desktop
    owner: "{{ general.user }}"
    mode: 0755
  tags:
    - configuration

- name: remove vagrant from login screen
  become: yes
  template:
    src: "roles/common/templates/vagrant.j2"
    dest: "/var/lib/AccountsService/users/vagrant"
    mode: 0644
  tags:
    - configuration
