# user.yml
---

- group: name=devbox state=present
  become: yes
- group: name=docker state=present
  become: yes
  tags:
    - user

# Define task to add user
- name: add user
  become: yes
  action: user name={{ user }} password={{ password }} update_password=always
               shell=/bin/bash home=/home/{{ user }}
  tags:
    - user

- user: name=devbox shell=/bin/bash group=devbox append=yes
  become: yes
  tags:
    - user

- user: name=devbox shell=/bin/bash group=docker append=yes
  become: yes
  tags:
    - user

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  tags:
    - user

- name: Add sudoers users to wheel group
  become: yes
  user: name=devbox groups=wheel append=yes state=present createhome=yes
  tags:
    - user
