# user.yml
---

- name: check if nvm installed
  become: yes
  become_user: "{{nvm.user}}"
  stat: path=~/.nvm
  register: nvm_path
  changed_when: False

- name: Install nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm.version }}
  become: yes
  become_user: "{{ nvm.user }}"
  tags: nvm

- name: source nvm in ~/.profile
  become: yes
  become_user: "{{nvm.user}}"
  lineinfile: >
    dest=~/.bash_profile
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: check installed node version
  become: yes
  become_user: "{{nvm.user}}"
  command: bash -c '. ~/.nvm/nvm.sh; nvm ls'
  register: nvm_install_result
  changed_when: False
  ignore_errors: True

- name: install nodejs using nvm
  become: yes
  become_user: "{{nvm.user}}"
  command: bash -c '. ~/.nvm/nvm.sh; nvm install {{ nvm.node_version }}'
  when: nvm_install_result|failed or nvm_install_result.stdout.find('{{nvm.node_version}}') == -1
  tags: nvm


# - name: Source nvm in ~/.profile
#   become: yes
#   become_user: "{{ nvm.user }}"
#   lineinfile: >
#     dest=~/.profile
#     line="source ~/.nvm/nvm.sh"
#     create=yes
#   tags: nvm
#
# - name: Install {{ nvm.node_version }}
#   command: bash -c '. ~/.nvm/nvm.sh; nvm install '
#   # register: nvm_install_result
#   # changed_when: "'is already installed.' not in nvm_install_result.stdout"
#   become: yes
#   become_user: "{{ nvm.user }}"
#   tags: nvm
#
# - name: Check if {{ nvm.node_version }} is the default node version
#   shell: sudo -iu {{ nvm.user }} source ~/.nvm/nvm.sh &&  sudo -iu {{ nvm.user }} nvm ls | grep -e 'default -> {{ nvm.node_version }}'
#   # register: nvm_check_default
#   # changed_when: False
#   become: yes
#   become_user: "{{ nvm.user }}"
#   ignore_errors: True
#   tags: nvm
#
# - name: Set default node version to {{ nvm.node_version }}
#   command: sudo -iu {{ nvm.user }} source ~/.nvm/nvm.sh && sudo -iu {{ nvm.user }} nvm alias default {{ nvm.node_version }}
#   # when: nvm_check_default|failed
#   become: yes
#   become_user: "{{ nvm.user }}"
#   tags: nvm
